sync from stereo, fix tools/release-to-stereo for relative paths (#330)
* tools/release-to-stereo - fix but with relative paths

If you called `./tools/release-to-stereo $TAG ../stereo`
then this would fail with a strange error about not being
a git directory.

The problem was that 'cd ../stereo' would be run from the
tempdir which would no longer be correct.

So the fix is to get the full patph to the dir and use that.

* pipelines/test/tw/INDEX.md - sync from stereo

These changes got made to the downstream file.
Sync them back in here.

diff --git a/tools/release-to-stereo b/tools/release-to-stereo
--- a/tools/release-to-stereo
+++ b/tools/release-to-stereo
@@ -93,7 +93,8 @@ main() {
 	tag=v${tag#v} # chop of 'v' in v0.0.1
 	shift
 
-	local stereo_dir="$1"
+	local stereo_diri="$1"
+	stereo_dir=$(cd "${stereo_diri}" && pwd) || fail "failed cd $stereo_dir"
 
 	TEMP_D=$(mktemp -d "${TMPDIR:-/tmp}/${0##*/}.XXXXXX") ||
 		fail "failed to make tempdir"
