tw-pip-check: replace tabs with spaces
Signed-off-by: dann frazier <dann.frazier@chainguard.dev>

diff --git a/tw-pip-check/tw-pip-check b/tw-pip-check/tw-pip-check
--- a/tw-pip-check/tw-pip-check
+++ b/tw-pip-check/tw-pip-check
@@ -39,13 +39,13 @@ if [ -z "$py" ]; then
     glob="/usr/bin/python3.[0-9][0-9] /usr/bin/python3.[789]"
     n=0
     for p in $glob; do
-	[ -x "$p" ] && n=$((n+1)) && py=$p
+      [ -x "$p" ] && n=$((n+1)) && py=$p
     done
     if [ "$n" -ne 1 ]; then
-	echo "ERROR: must pass --python: " \
-	     "found $n executables matching $glob"
-	[ "$n" -eq 0 ] || echo "found:" $glob
-	exit 1
+      echo "ERROR: must pass --python: " \
+           "found $n executables matching $glob"
+      [ "$n" -eq 0 ] || echo "found:" $glob
+      exit 1
     fi
     echo "using python: $py"
 fi
